version: 2.1
orbs:
  node: circleci/node@4
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: node --version
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-deps-
      - run: npm ci
      - run: npx cypress cache list
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            # NPM module cache
            ~/.npm
            # Cypress binaries are stored here
            # according to https://on.cypress.io/caching
            ~/.cache/Cypress
